export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  variables: Record<string, string>;
}

export const themePresets: ThemePreset[] = [
  {
    id: "arctic-default",
    name: "Arctic Default",
    description: "The signature Power Plunge look — dark with icy cyan accents",
    variables: {
      "--theme-bg": "#030712",
      "--theme-bg-card": "#111827",
      "--theme-bg-elevated": "#1f2937",
      "--theme-text": "#f9fafb",
      "--theme-text-muted": "#9ca3af",
      "--theme-primary": "#67e8f9",
      "--theme-primary-hover": "#22d3ee",
      "--theme-primary-muted": "rgba(103,232,249,0.15)",
      "--theme-accent": "#06b6d4",
      "--theme-border": "#374151",
      "--theme-success": "#34d399",
      "--theme-error": "#f87171",
      "--theme-warning": "#fbbf24",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    description: "Deep navy tones with electric blue highlights",
    variables: {
      "--theme-bg": "#0a0e1a",
      "--theme-bg-card": "#111936",
      "--theme-bg-elevated": "#1a2347",
      "--theme-text": "#e8ecf4",
      "--theme-text-muted": "#8892b0",
      "--theme-primary": "#60a5fa",
      "--theme-primary-hover": "#3b82f6",
      "--theme-primary-muted": "rgba(96,165,250,0.15)",
      "--theme-accent": "#2563eb",
      "--theme-border": "#1e3a5f",
      "--theme-success": "#4ade80",
      "--theme-error": "#fb7185",
      "--theme-warning": "#facc15",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "emerald-dark",
    name: "Emerald Dark",
    description: "Rich dark greens evoking natural vitality",
    variables: {
      "--theme-bg": "#071210",
      "--theme-bg-card": "#0d211d",
      "--theme-bg-elevated": "#143129",
      "--theme-text": "#ecfdf5",
      "--theme-text-muted": "#86b5a4",
      "--theme-primary": "#34d399",
      "--theme-primary-hover": "#10b981",
      "--theme-primary-muted": "rgba(52,211,153,0.15)",
      "--theme-accent": "#059669",
      "--theme-border": "#1a3d33",
      "--theme-success": "#4ade80",
      "--theme-error": "#f87171",
      "--theme-warning": "#fde68a",
      "--theme-radius": "0.75rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "sunset-warmth",
    name: "Sunset Warmth",
    description: "Warm amber and orange tones on dark canvas",
    variables: {
      "--theme-bg": "#120c07",
      "--theme-bg-card": "#1f1610",
      "--theme-bg-elevated": "#2d2017",
      "--theme-text": "#fef3e2",
      "--theme-text-muted": "#c4a882",
      "--theme-primary": "#fb923c",
      "--theme-primary-hover": "#f97316",
      "--theme-primary-muted": "rgba(251,146,60,0.15)",
      "--theme-accent": "#ea580c",
      "--theme-border": "#44311d",
      "--theme-success": "#86efac",
      "--theme-error": "#fca5a5",
      "--theme-warning": "#fde047",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    description: "Regal violet tones with soft purple accents",
    variables: {
      "--theme-bg": "#0d0a14",
      "--theme-bg-card": "#1a1425",
      "--theme-bg-elevated": "#261e36",
      "--theme-text": "#f3f0ff",
      "--theme-text-muted": "#a78bcc",
      "--theme-primary": "#c084fc",
      "--theme-primary-hover": "#a855f7",
      "--theme-primary-muted": "rgba(192,132,252,0.15)",
      "--theme-accent": "#9333ea",
      "--theme-border": "#3b2d52",
      "--theme-success": "#6ee7b7",
      "--theme-error": "#fda4af",
      "--theme-warning": "#fcd34d",
      "--theme-radius": "0.625rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    description: "Elegant rose and pink on charcoal",
    variables: {
      "--theme-bg": "#120b0e",
      "--theme-bg-card": "#1f1419",
      "--theme-bg-elevated": "#2d1d24",
      "--theme-text": "#fdf2f8",
      "--theme-text-muted": "#c9929e",
      "--theme-primary": "#fb7185",
      "--theme-primary-hover": "#f43f5e",
      "--theme-primary-muted": "rgba(251,113,133,0.15)",
      "--theme-accent": "#e11d48",
      "--theme-border": "#4a2332",
      "--theme-success": "#86efac",
      "--theme-error": "#fca5a5",
      "--theme-warning": "#fde68a",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    description: "Clean neutral grays for a minimalist aesthetic",
    variables: {
      "--theme-bg": "#0f1114",
      "--theme-bg-card": "#1c1e22",
      "--theme-bg-elevated": "#292b30",
      "--theme-text": "#eaedf0",
      "--theme-text-muted": "#888d96",
      "--theme-primary": "#94a3b8",
      "--theme-primary-hover": "#cbd5e1",
      "--theme-primary-muted": "rgba(148,163,184,0.15)",
      "--theme-accent": "#64748b",
      "--theme-border": "#363a42",
      "--theme-success": "#4ade80",
      "--theme-error": "#f87171",
      "--theme-warning": "#fbbf24",
      "--theme-radius": "0.375rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "ocean-teal",
    name: "Ocean Teal",
    description: "Deep ocean blues merging into warm teal",
    variables: {
      "--theme-bg": "#061014",
      "--theme-bg-card": "#0c1d24",
      "--theme-bg-elevated": "#132a34",
      "--theme-text": "#ecfeff",
      "--theme-text-muted": "#7cb8c7",
      "--theme-primary": "#2dd4bf",
      "--theme-primary-hover": "#14b8a6",
      "--theme-primary-muted": "rgba(45,212,191,0.15)",
      "--theme-accent": "#0d9488",
      "--theme-border": "#1a3d44",
      "--theme-success": "#6ee7b7",
      "--theme-error": "#fda4af",
      "--theme-warning": "#fde047",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "golden-luxury",
    name: "Golden Luxury",
    description: "Premium gold accents on deep black",
    variables: {
      "--theme-bg": "#0a0904",
      "--theme-bg-card": "#161408",
      "--theme-bg-elevated": "#221f0e",
      "--theme-text": "#fefce8",
      "--theme-text-muted": "#bba654",
      "--theme-primary": "#eab308",
      "--theme-primary-hover": "#ca8a04",
      "--theme-primary-muted": "rgba(234,179,8,0.12)",
      "--theme-accent": "#a16207",
      "--theme-border": "#3d370f",
      "--theme-success": "#86efac",
      "--theme-error": "#fca5a5",
      "--theme-warning": "#fde68a",
      "--theme-radius": "0.25rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "nordic-frost",
    name: "Nordic Frost",
    description: "Crisp white-on-dark with icy silver highlights",
    variables: {
      "--theme-bg": "#090b10",
      "--theme-bg-card": "#12151c",
      "--theme-bg-elevated": "#1c2028",
      "--theme-text": "#f0f4f8",
      "--theme-text-muted": "#8c95a4",
      "--theme-primary": "#e2e8f0",
      "--theme-primary-hover": "#f1f5f9",
      "--theme-primary-muted": "rgba(226,232,240,0.12)",
      "--theme-accent": "#94a3b8",
      "--theme-border": "#2a3040",
      "--theme-success": "#6ee7b7",
      "--theme-error": "#fda4af",
      "--theme-warning": "#fde047",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
  {
    id: "sun-stoppers",
    name: "Sun Stoppers",
    description: "Bold amber and golden tones radiating warmth on deep charcoal",
    variables: {
      "--theme-bg": "#0e0c08",
      "--theme-bg-card": "#1a1710",
      "--theme-bg-elevated": "#272218",
      "--theme-text": "#fdf6e8",
      "--theme-text-muted": "#b8a67a",
      "--theme-primary": "#f9a633",
      "--theme-primary-hover": "#e8922a",
      "--theme-primary-muted": "rgba(249,166,51,0.14)",
      "--theme-accent": "#d4890e",
      "--theme-border": "#3a3120",
      "--theme-success": "#86efac",
      "--theme-error": "#f87171",
      "--theme-warning": "#fde68a",
      "--theme-radius": "0.5rem",
      "--theme-font": "'Inter', sans-serif",
    },
  },
];
